/**
 * Platform built-in security policies (Wisbility defaults).
 * Customers may edit, clone, or disable these policies.
 */
export const DEFAULT_SECURITY_POLICIES = [
  {
    policyKey: "builtin_disabled_computer",
    name: "Disabled Computer",
    enabled: true,
    riskLevel: "low",
    conditions: ["DISABLED_COMPUTER"],
    conditionMode: "AND",
    description: "Computer account is disabled in Active Directory.",
    recommendation: "Review and remove stale disabled computer objects.",
    builtIn: true,
  },
  {
    policyKey: "builtin_dormant_computer",
    name: "Dormant Computer",
    enabled: true,
    riskLevel: "medium",
    conditions: ["DISABLED_COMPUTER", "INACTIVE_OVER:90"],
    conditionMode: "AND",
    description: "Disabled computer with extended inactivity.",
    recommendation: "Decommission or document retained disabled computer objects.",
    builtIn: true,
  },
  {
    policyKey: "builtin_inactive_computer",
    name: "Inactive Computer",
    enabled: true,
    riskLevel: "medium",
    conditions: ["INACTIVE_COMPUTER", "INACTIVE_OVER:90"],
    conditionMode: "AND",
    description: "Computer has not authenticated recently.",
    recommendation: "Review stale computer accounts and remove if unused.",
    builtIn: true,
  },
  {
    policyKey: "builtin_disabled_user",
    name: "Disabled User Account",
    enabled: true,
    riskLevel: "medium",
    conditions: ["DISABLED_USER"],
    conditionMode: "AND",
    description: "User account is disabled.",
    recommendation: "Review disabled accounts for deprovisioning or archival.",
    builtIn: true,
  },
  {
    policyKey: "builtin_inactive_user",
    name: "Inactive User Account",
    enabled: true,
    riskLevel: "medium",
    conditions: ["INACTIVE_USER", "INACTIVE_OVER:90"],
    conditionMode: "AND",
    description: "Enabled user with no recent logon activity.",
    recommendation: "Investigate accounts with no recent logon; disable or remove if no longer needed.",
    builtIn: true,
  },
  {
    policyKey: "builtin_dormant_privileged_user",
    name: "Dormant Privileged User",
    enabled: true,
    riskLevel: "critical",
    conditions: ["PRIVILEGED_USER", "INACTIVE_OVER:90"],
    conditionMode: "AND",
    description: "Privileged account inactive for an extended period.",
    recommendation: "Revoke privileged access or confirm continued business need immediately.",
    builtIn: true,
  },
  {
    policyKey: "builtin_weak_privileged_account",
    name: "Weak Privileged Account",
    enabled: true,
    riskLevel: "critical",
    conditions: ["PASSWORD_NEVER_EXPIRES", "PRIVILEGED_USER"],
    conditionMode: "AND",
    description: "Privileged account with password never expires.",
    recommendation: "Enforce password rotation and privileged access controls.",
    builtIn: true,
  },
  {
    policyKey: "builtin_password_never_expires",
    name: "Password Never Expires",
    enabled: true,
    riskLevel: "medium",
    conditions: ["PASSWORD_NEVER_EXPIRES"],
    conditionMode: "AND",
    description: "Account configured with non-expiring password.",
    recommendation: "Enforce password rotation unless a documented exception exists.",
    builtIn: true,
  },
  {
    policyKey: "builtin_password_not_required",
    name: "Password Not Required",
    enabled: true,
    riskLevel: "critical",
    conditions: ["PASSWORD_NOT_REQUIRED"],
    conditionMode: "AND",
    description: "Account does not require a password.",
    recommendation: "Require passwords for all interactive user accounts.",
    builtIn: true,
  },
  {
    policyKey: "builtin_locked_account",
    name: "Locked Account",
    enabled: true,
    riskLevel: "high",
    conditions: ["LOCKED_ACCOUNT"],
    conditionMode: "AND",
    description: "Account is locked due to lockout policy.",
    recommendation: "Unlock legitimate users or investigate brute-force lockouts.",
    builtIn: true,
  },
  {
    policyKey: "builtin_kerberoastable",
    name: "Kerberoastable Account",
    enabled: true,
    riskLevel: "high",
    conditions: ["KERBEROASTABLE_ACCOUNT"],
    conditionMode: "AND",
    description: "Account exposes service principal names for offline cracking.",
    recommendation: "Use gMSA/MSA, enforce strong service account passwords, and audit SPNs.",
    builtIn: true,
  },
  {
    policyKey: "builtin_shadow_admin",
    name: "Shadow Admin",
    enabled: true,
    riskLevel: "critical",
    conditions: ["SHADOW_ADMIN"],
    conditionMode: "AND",
    description: "Non-standard ACL grants administrative rights.",
    recommendation: "Remove unintended administrative ACL grants.",
    builtIn: true,
  },
  {
    policyKey: "builtin_privilege_escalation",
    name: "Privilege Escalation Path",
    enabled: true,
    riskLevel: "high",
    conditions: ["PRIVILEGE_ESCALATION_PATH"],
    conditionMode: "AND",
    description: "Identity graph shows a path to elevated privileges.",
    recommendation: "Break escalation paths and enforce least privilege.",
    builtIn: true,
  },
  {
    policyKey: "builtin_unconstrained_delegation",
    name: "Unconstrained Delegation",
    enabled: true,
    riskLevel: "critical",
    conditions: ["UNCONSTRAINED_DELEGATION"],
    conditionMode: "AND",
    description: "Account trusted for unconstrained Kerberos delegation.",
    recommendation: "Remove unconstrained delegation or constrain to specific services.",
    builtIn: true,
  },
  {
    policyKey: "builtin_empty_group",
    name: "Empty Group",
    enabled: true,
    riskLevel: "low",
    conditions: ["EMPTY_GROUP"],
    conditionMode: "AND",
    description: "Security group has no members.",
    recommendation: "Remove unused groups or document business justification.",
    builtIn: true,
  },
  {
    policyKey: "builtin_service_account",
    name: "Service Account",
    enabled: true,
    riskLevel: "low",
    conditions: ["SERVICE_ACCOUNT"],
    conditionMode: "AND",
    description: "User object with registered service principal names.",
    recommendation: "Inventory service accounts; enforce gMSA/MSA and least privilege.",
    builtIn: true,
  },
  {
    policyKey: "builtin_inactive_user_180d",
    name: "Long-Term Inactive User (>180 days)",
    enabled: true,
    riskLevel: "high",
    conditions: ["INACTIVE_USER", "INACTIVE_OVER:180"],
    conditionMode: "AND",
    description: "User inactive for more than 180 days.",
    recommendation: "Disable or remove accounts with no logon in 180+ days.",
    builtIn: true,
  },
  {
    policyKey: "builtin_deep_nested_group",
    name: "Deep Nested Group (>5 levels)",
    enabled: true,
    riskLevel: "high",
    conditions: ["NESTED_GROUP", "NESTED_DEPTH_OVER:5"],
    conditionMode: "AND",
    description: "Group nesting exceeds five levels.",
    recommendation: "Flatten group structure to reduce privilege inheritance risk.",
    builtIn: true,
  },
  {
    policyKey: "builtin_large_group",
    name: "Large Group (>1000 members)",
    enabled: true,
    riskLevel: "medium",
    conditions: ["MEMBER_COUNT_OVER:1000"],
    conditionMode: "AND",
    description: "Group membership exceeds 1000 members.",
    recommendation: "Review large groups for least-privilege and ownership.",
    builtIn: true,
  },
  {
    policyKey: "builtin_kerberos_or_asrep",
    name: "Kerberos Attack Surface (OR)",
    enabled: false,
    riskLevel: "critical",
    conditions: ["KERBEROASTABLE_ACCOUNT", "ASREP_ROASTABLE_USER"],
    conditionMode: "OR",
    description: "Example OR policy: kerberoastable or AS-REP roastable account.",
    recommendation: "Harden service accounts and enable Kerberos pre-authentication.",
    builtIn: true,
  },
  {
    policyKey: "builtin_asrep_roastable",
    name: "AS-REP Roastable User",
    enabled: true,
    riskLevel: "high",
    conditions: ["ASREP_ROASTABLE_USER"],
    conditionMode: "AND",
    description: "User does not require Kerberos pre-authentication.",
    recommendation: "Enable Kerberos pre-authentication unless a documented exception exists.",
    builtIn: true,
  },
  {
    policyKey: "builtin_constrained_delegation",
    name: "Constrained Delegation",
    enabled: true,
    riskLevel: "high",
    conditions: ["CONSTRAINED_DELEGATION"],
    conditionMode: "AND",
    description: "Account is trusted for constrained Kerberos delegation.",
    recommendation: "Review constrained delegation targets and remove unused trust.",
    builtIn: true,
  },
  {
    policyKey: "builtin_rbcd",
    name: "Resource-Based Constrained Delegation",
    enabled: true,
    riskLevel: "critical",
    conditions: ["RBCD_CONFIGURED"],
    conditionMode: "AND",
    description: "Computer allows resource-based constrained delegation.",
    recommendation: "Audit msDS-AllowedToActOnBehalfOfOtherIdentity and remove unintended principals.",
    builtIn: true,
  },
  {
    policyKey: "builtin_excessive_privileges",
    name: "Excessive Privileges",
    enabled: true,
    riskLevel: "high",
    conditions: ["EXCESSIVE_PRIVILEGES"],
    conditionMode: "AND",
    description: "Identity has an excessive number of privileged group paths.",
    recommendation: "Reduce privileged group memberships to least privilege.",
    builtIn: true,
  },
  {
    policyKey: "builtin_toxic_privilege",
    name: "Toxic Privilege Combination",
    enabled: true,
    riskLevel: "critical",
    conditions: ["TOXIC_PRIVILEGE_COMBINATION"],
    conditionMode: "AND",
    description: "Identity holds conflicting privileged group memberships.",
    recommendation: "Split duties and remove toxic privilege combinations.",
    builtIn: true,
  },
  {
    policyKey: "builtin_nested_privileged",
    name: "Nested Privileged Access",
    enabled: true,
    riskLevel: "high",
    conditions: ["NESTED_PRIVILEGED_ACCESS"],
    conditionMode: "AND",
    description: "Privileged access inherited through nested group membership.",
    recommendation: "Flatten privileged nesting and audit inherited memberships.",
    builtIn: true,
  },
  {
    policyKey: "builtin_broken_acl",
    name: "Broken ACL",
    enabled: true,
    riskLevel: "high",
    conditions: ["BROKEN_ACL"],
    conditionMode: "AND",
    description: "Security descriptor contains broken or empty sensitive ACL entries.",
    recommendation: "Repair ACL inheritance and remove orphan ACE targets.",
    builtIn: true,
  },
  {
    policyKey: "builtin_sid_history",
    name: "SID History Risk",
    enabled: true,
    riskLevel: "high",
    conditions: ["SID_HISTORY_RISK"],
    conditionMode: "AND",
    description: "Account carries SID history that may retain elevated rights.",
    recommendation: "Clear SID history after migrations unless explicitly required.",
    builtIn: true,
  },
  {
    policyKey: "builtin_reversible_encryption",
    name: "Reversible Encryption Enabled",
    enabled: true,
    riskLevel: "critical",
    conditions: ["REVERSIBLE_ENCRYPTION_ENABLED"],
    conditionMode: "AND",
    description: "Account allows reversible password encryption.",
    recommendation: "Disable reversible encryption unless required by a documented application.",
    builtIn: true,
  },
  {
    policyKey: "builtin_spn_misconfiguration",
    name: "SPN Misconfiguration",
    enabled: true,
    riskLevel: "high",
    conditions: ["SPN_MISCONFIGURATION"],
    conditionMode: "AND",
    description: "Service principal name registration is malformed or conflicting.",
    recommendation: "Correct or remove duplicate/malformed SPNs.",
    builtIn: true,
  },
  {
    policyKey: "builtin_unsupported_os",
    name: "Unsupported Operating System",
    enabled: true,
    riskLevel: "high",
    conditions: ["UNSUPPORTED_OS"],
    conditionMode: "AND",
    description: "Computer reports an unsupported OS version.",
    recommendation: "Upgrade or isolate computers running unsupported OS versions.",
    builtIn: true,
  },
];
