import {
  GROUP_LDAP_SECURITY_FEATURES,
  USER_ACCOUNT_SECURITY_FEATURES,
  COMPUTER_SECURITY_FEATURES,
  KERBEROS_SECURITY_FEATURES,
  DELEGATION_SECURITY_FEATURES,
  GROUP_INTELLIGENCE_FEATURES,
  PRIVILEGED_ACCESS_FEATURES,
  ACL_INTELLIGENCE_FEATURES,
} from "./postureFeatureIds.js";

export const POSTURE_FEATURE_CATEGORIES = [
  { id: "user_security", label: "User Security" },
  { id: "group_security", label: "Group Security" },
  { id: "privileged_access", label: "Privileged Access" },
  { id: "computer_security", label: "Computer Security" },
  { id: "kerberos_delegation", label: "Kerberos & Delegation" },
  { id: "acl_intelligence", label: "ACL Intelligence" },
];

export const POSTURE_SCAN_BUNDLES = [
  { id: "disabled_users", label: "Disabled Users", featureIds: ["disabled_users"], defaultEnabled: true },
  { id: "inactive_users", label: "Inactive Users", featureIds: ["inactive_users"], defaultEnabled: true },
  { id: "locked_accounts", label: "Locked Accounts", featureIds: ["locked_accounts"], defaultEnabled: true },
  { id: "empty_groups", label: "Empty Groups", featureIds: ["empty_groups", "unused_groups"], defaultEnabled: true },
  { id: "nested_groups", label: "Nested Groups", featureIds: ["nested_groups", "circular_memberships"], defaultEnabled: true },
  {
    id: "privileged_access",
    label: "Privileged Access",
    featureIds: [
      "nested_privileged_access",
      "dormant_privileged_users",
      "excessive_privileges",
      "privilege_escalation_paths",
      "toxic_privilege_combinations",
    ],
    defaultEnabled: true,
  },
  {
    id: "delegation_risks",
    label: "Delegation Risks",
    featureIds: [
      "unconstrained_delegation",
      "constrained_delegation",
      "rbcd",
      // "delegation_exposure", // disabled — Delegation Exposure Summary
    ],
    defaultEnabled: true,
  },
  {
    id: "computer_risks",
    label: "Computer Risks",
    featureIds: [...COMPUTER_SECURITY_FEATURES],
    defaultEnabled: true,
  },
  {
    id: "kerberos_risks",
    label: "Kerberos Risks",
    featureIds: [...KERBEROS_SECURITY_FEATURES],
    defaultEnabled: true,
  },
  { id: "acl_risks", label: "ACL Risks", featureIds: ["orphan_sids", "shadow_admins", "sid_history_analysis", "foreign_security_principals", "unknown_sid_bindings", "broken_acls"], defaultEnabled: true },
];

const IMPLEMENTED = new Set([
  ...USER_ACCOUNT_SECURITY_FEATURES,
  ...GROUP_LDAP_SECURITY_FEATURES,
  ...COMPUTER_SECURITY_FEATURES,
  ...KERBEROS_SECURITY_FEATURES,
  ...DELEGATION_SECURITY_FEATURES,
  ...GROUP_INTELLIGENCE_FEATURES,
  ...PRIVILEGED_ACCESS_FEATURES,
  ...ACL_INTELLIGENCE_FEATURES,
]);

const REGISTRY = [
  {
    id: "disabled_users",
    name: "Disabled Users",
    description: "Accounts disabled via userAccountControl or inactive status.",
    category: "user_security",
    riskLevel: "medium",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "user_account_security",
    requiredAttributes: ["sAMAccountName", "displayName", "mail", "userAccountControl"],
    ldapFilter:
      "(&(objectCategory=person)(objectClass=user)(userAccountControl:1.2.840.113556.1.4.803:=2))",
    recommendation: "Review disabled accounts for deprovisioning or archival.",
  },
  {
    id: "inactive_users",
    name: "Inactive Users",
    description: "Enabled accounts with no recent logon activity (configurable day threshold).",
    category: "user_security",
    riskLevel: "medium",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "user_account_security",
    requiredAttributes: ["sAMAccountName", "lastLogonTimestamp", "userAccountControl"],
    ldapFilter:
      "(&(objectCategory=person)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))",
    recommendation: "Investigate accounts with no recent logon; disable or remove if no longer needed.",
    settings: [
      {
        key: "inactiveDays",
        label: "Inactivity threshold (days)",
        type: "number",
        default: 90,
        min: 1,
        max: 3650,
        description:
          "Flag enabled accounts whose lastLogonTimestamp is older than this many days.",
      },
    ],
  },
  {
    id: "locked_accounts",
    name: "Locked Accounts",
    description: "Accounts locked by lockout or LOCKOUT flag.",
    category: "user_security",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "user_account_security",
    requiredAttributes: ["sAMAccountName", "lockoutTime", "userAccountControl"],
    ldapFilter:
      "(&(objectCategory=person)(objectClass=user)(|(lockoutTime>=1)(userAccountControl:1.2.840.113556.1.4.803:=16)))",
    recommendation: "Unlock legitimate users or investigate brute-force lockouts.",
  },
  {
    id: "password_never_expires",
    name: "Password Never Expires",
    description: "Accounts with DONT_EXPIRE_PASSWD flag set.",
    category: "user_security",
    riskLevel: "medium",
    defaultEnabled: false,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "user_account_security",
    requiredAttributes: ["sAMAccountName", "userAccountControl"],
    ldapFilter:
      "(&(objectCategory=person)(objectClass=user)(userAccountControl:1.2.840.113556.1.4.803:=65536))",
    recommendation: "Enforce password rotation unless a documented exception exists.",
  },
  {
    id: "password_not_required",
    name: "Password Not Required",
    description: "Accounts that can authenticate without a password.",
    category: "user_security",
    riskLevel: "critical",
    defaultEnabled: false,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "user_account_security",
    requiredAttributes: ["sAMAccountName", "userAccountControl"],
    ldapFilter:
      "(&(objectCategory=person)(objectClass=user)(userAccountControl:1.2.840.113556.1.4.803:=32))",
    recommendation: "Require passwords for all interactive user accounts.",
  },
  {
    id: "reversible_encryption_enabled",
    name: "Reversible Encryption Enabled",
    description: "Accounts storing passwords with reversible encryption.",
    category: "user_security",
    riskLevel: "critical",
    defaultEnabled: false,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "user_account_security",
    requiredAttributes: ["sAMAccountName", "userAccountControl"],
    ldapFilter:
      "(&(objectCategory=person)(objectClass=user)(userAccountControl:1.2.840.113556.1.4.803:=128))",
    recommendation: "Disable reversible encryption; use strong hashing only.",
  },
  {
    id: "smartcard_not_required",
    name: "Smartcard Not Required",
    description: "Accounts not requiring smart card logon.",
    category: "user_security",
    riskLevel: "medium",
    defaultEnabled: false,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "user_account_security",
    requiredAttributes: ["sAMAccountName", "userAccountControl"],
    ldapFilter:
      "(&(objectCategory=person)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=262144)))",
    recommendation: "Require smart card logon for privileged accounts where policy applies.",
  },
  {
    id: "service_accounts",
    name: "Service Accounts",
    description: "User objects with service principal names (SPNs).",
    category: "user_security",
    riskLevel: "low",
    defaultEnabled: false,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "user_account_security",
    requiredAttributes: ["sAMAccountName", "servicePrincipalName"],
    ldapFilter: "(&(objectCategory=person)(objectClass=user)(servicePrincipalName=*))",
    recommendation: "Inventory service accounts; enforce gMSA/MSA and least privilege.",
  },
  {
    id: "empty_groups",
    name: "Empty Groups",
    description: "Groups with no member attribute in Active Directory.",
    category: "group_security",
    riskLevel: "low",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "group_ldap_security",
    requiredAttributes: ["member", "cn", "distinguishedName"],
    ldapFilter: "(&(objectCategory=group)(objectClass=group)(!(member=*)))",
    recommendation: "Remove unused groups or document business justification.",
  },
  {
    id: "groups_without_owners",
    name: "Groups Without Owner",
    description: "Groups missing owner or managedBy metadata.",
    category: "group_security",
    riskLevel: "medium",
    defaultEnabled: false,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "group_ldap_security",
    requiredAttributes: ["managedBy", "description"],
    ldapFilter: "(&(objectCategory=group)(objectClass=group)(!(managedBy=*)))",
    recommendation: "Assign a group owner or manager for accountability.",
  },
  {
    id: "nested_groups",
    name: "Nested Groups",
    description: "Deep group nesting expanding privilege inheritance scope.",
    category: "group_security",
    riskLevel: "medium",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "group_ldap_security",
    requiredAttributes: ["member"],
    ldapFilter: "(&(objectCategory=group)(objectClass=group))",
    recommendation: "Review deep nesting; privilege inheritance expands with depth.",
  },
  {
    id: "unused_groups",
    name: "Unused Groups",
    description: "Groups with no members and not referenced by other groups.",
    category: "group_security",
    riskLevel: "low",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "group_ldap_security",
    requiredAttributes: ["member", "memberOf"],
    ldapFilter: "(&(objectCategory=group)(objectClass=group))",
    recommendation: "Consider decommissioning unused groups.",
  },
  {
    id: "orphan_groups",
    name: "Orphan Groups",
    description: "Empty groups with no owner and no parent membership.",
    category: "group_security",
    riskLevel: "medium",
    defaultEnabled: false,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "group_ldap_security",
    requiredAttributes: ["member", "memberOf", "managedBy"],
    ldapFilter: "(&(objectCategory=group)(objectClass=group))",
    recommendation: "Validate AD hygiene for disconnected groups.",
  },
  {
    id: "circular_memberships",
    name: "Circular Memberships",
    description: "Circular nested group chains.",
    category: "group_security",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "group_ldap_security",
    requiredAttributes: ["member"],
    ldapFilter: "(&(objectCategory=group)(objectClass=group))",
    recommendation: "Break circular group nesting to prevent unbounded inheritance.",
  },
  {
    id: "duplicate_groups",
    name: "Duplicate Groups",
    description: "Groups with identical membership signatures.",
    category: "group_security",
    riskLevel: "low",
    defaultEnabled: false,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "group_ldap_security",
    requiredAttributes: ["member"],
    ldapFilter: "(&(objectCategory=group)(objectClass=group))",
    recommendation: "Consolidate groups with identical membership sets.",
  },
  {
    id: "nested_privileged_access",
    name: "Nested Privileged Access",
    description: "Privileged access reachable via nested group chains.",
    category: "privileged_access",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    supportsSearchBase: true,
    moduleId: "group_ldap_security",
    objectTypes: ["group"],
    searchScope: "Subtree",
    requiredAttributes: ["member", "memberOf"],
    ldapFilter: "(&(objectCategory=group)(objectClass=group))",
    recommendation: "Review parent groups granting inherited privileged access.",
  },
  {
    id: "dormant_privileged_users",
    name: "Dormant Privileged Users",
    description: "Inactive accounts with privileged group paths.",
    category: "privileged_access",
    riskLevel: "critical",
    defaultEnabled: true,
    requiresGraph: true,
    requiresAdLdap: false,
    executionMode: "HYBRID",
    supportsSearchBase: true,
    moduleId: "identity_graph_security",
    objectTypes: ["user"],
    searchScope: "Subtree",
    requiredAttributes: ["lastLogonTimestamp", "memberOf"],
    ldapFilter: "(&(objectCategory=person)(objectClass=user))",
    recommendation: "Remove privileged access from inactive accounts immediately.",
  },
  {
    id: "toxic_privilege_combinations",
    name: "Toxic Privilege Combinations",
    description: "Users with multiple privileged group paths (SoD risk).",
    category: "privileged_access",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: true,
    requiresAdLdap: false,
    executionMode: "HYBRID",
    supportsSearchBase: true,
    moduleId: "identity_graph_security",
    objectTypes: ["user"],
    searchScope: "Subtree",
    requiredAttributes: ["memberOf"],
    ldapFilter: "(&(objectCategory=person)(objectClass=user))",
    recommendation: "Review separation of duties and least privilege.",
  },
  {
    id: "excessive_privileges",
    name: "Excessive Privileges",
    description: "Users with excessive privileged path count.",
    category: "privileged_access",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: true,
    requiresAdLdap: false,
    executionMode: "HYBRID",
    supportsSearchBase: true,
    moduleId: "identity_graph_security",
    objectTypes: ["user"],
    searchScope: "Subtree",
    requiredAttributes: ["memberOf"],
    ldapFilter: "(&(objectCategory=person)(objectClass=user))",
    recommendation: "Reduce privilege sprawl and nested admin paths.",
  },
  {
    id: "privilege_escalation_paths",
    name: "Privilege Escalation Paths",
    description: "Indirect paths to privileged groups via nesting.",
    category: "privileged_access",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: true,
    requiresAdLdap: false,
    executionMode: "HYBRID",
    supportsSearchBase: true,
    moduleId: "identity_graph_security",
    objectTypes: ["user"],
    searchScope: "Subtree",
    requiredAttributes: ["memberOf"],
    ldapFilter: "(&(objectCategory=person)(objectClass=user))",
    recommendation: "Shorten nesting chains to privileged groups.",
  },
  {
    id: "unconstrained_delegation",
    name: "Unconstrained Delegation",
    description: "Accounts trusted for unconstrained Kerberos delegation (TrustedForDelegation).",
    category: "kerberos_delegation",
    riskLevel: "critical",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "delegation_security",
    objectTypes: ["user", "computer"],
    searchScope: "Subtree",
    requiredAttributes: ["userAccountControl", "msDS-AllowedToDelegateTo"],
    ldapFilter:
      "(&(objectCategory=*)(userAccountControl:1.2.840.113556.1.4.803:=524288))",
    recommendation: "Replace unconstrained delegation with constrained or RBCD.",
  },
  {
    id: "disabled_computers",
    name: "Disabled Computers",
    description: "Computer accounts disabled via userAccountControl.",
    category: "computer_security",
    riskLevel: "low",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "computer_security",
    requiredAttributes: ["sAMAccountName", "userAccountControl", "distinguishedName"],
    ldapFilter: "(&(objectCategory=computer)(objectClass=computer))",
    recommendation: "Review and remove stale disabled computer objects.",
  },
  {
    id: "inactive_computers",
    name: "Inactive Computers",
    description: "Enabled computers with no recent logon (configurable day threshold).",
    category: "computer_security",
    riskLevel: "medium",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "computer_security",
    requiredAttributes: ["lastLogonTimestamp", "userAccountControl"],
    ldapFilter: "(&(objectCategory=computer)(objectClass=computer))",
    recommendation: "Review stale computer accounts.",
    settings: [
      {
        key: "inactiveDays",
        label: "Inactivity threshold (days)",
        type: "number",
        default: 90,
        min: 30,
        max: 180,
        description: "Supported thresholds: 30, 60, 90, 180 days.",
      },
    ],
  },
  {
    id: "missing_os_information",
    name: "Missing OS Information",
    description: "Computer objects without operatingSystem populated.",
    category: "computer_security",
    riskLevel: "medium",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "computer_security",
    requiredAttributes: ["operatingSystem", "operatingSystemVersion"],
    ldapFilter: "(&(objectCategory=computer)(objectClass=computer))",
    recommendation: "Populate OS inventory information.",
  },
  {
    id: "unsupported_os_versions",
    name: "Unsupported Operating Systems",
    description: "Computers running legacy OS versions (configurable list).",
    category: "computer_security",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "computer_security",
    requiredAttributes: ["operatingSystem", "operatingSystemVersion"],
    ldapFilter: "(&(objectCategory=computer)(objectClass=computer))",
    recommendation: "Upgrade unsupported operating systems.",
  },
  {
    id: "servers_in_wrong_ou",
    name: "Servers in Workstation OU",
    description: "Server OS computers placed in workstation/desktop OUs.",
    category: "computer_security",
    riskLevel: "medium",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "computer_security",
    requiredAttributes: ["distinguishedName", "operatingSystem"],
    ldapFilter: "(&(objectCategory=computer)(objectClass=computer))",
    recommendation: "Review OU placement.",
  },
  {
    id: "duplicate_spns",
    name: "Duplicate SPNs",
    description: "Duplicate servicePrincipalName values across users and computers.",
    category: "computer_security",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "computer_security",
    requiredAttributes: ["servicePrincipalName"],
    ldapFilter: "(&(objectCategory=computer)(objectClass=computer))",
    recommendation: "Resolve duplicate SPNs.",
  },
  {
    id: "computers_without_owners",
    name: "Computers Without Owners",
    description: "Computer objects missing managedBy / owner metadata.",
    category: "computer_security",
    riskLevel: "medium",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "computer_security",
    requiredAttributes: ["managedBy", "distinguishedName"],
    ldapFilter: "(&(objectCategory=computer)(objectClass=computer))",
    recommendation: "Assign accountable owner.",
  },
  {
    id: "kerberoastable_accounts",
    name: "Kerberoastable Accounts",
    description: "Accounts with servicePrincipalName populated (Kerberoasting exposure).",
    category: "kerberos_delegation",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "kerberos_security",
    objectTypes: ["user"],
    searchScope: "Subtree",
    requiredAttributes: ["servicePrincipalName", "userAccountControl"],
    ldapFilter: "(&(objectCategory=person)(objectClass=user)(servicePrincipalName=*))",
    recommendation: "Review service account exposure.",
  },
  {
    id: "asrep_roastable_users",
    name: "AS-REP Roastable Users",
    description: "Accounts with DONT_REQ_PREAUTH (UAC 4194304) enabled.",
    category: "kerberos_delegation",
    riskLevel: "critical",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "kerberos_security",
    objectTypes: ["user"],
    searchScope: "Subtree",
    requiredAttributes: ["userAccountControl"],
    ldapFilter:
      "(&(objectCategory=person)(objectClass=user)(userAccountControl:1.2.840.113556.1.4.803:=4194304))",
    recommendation: "Enable Kerberos pre-authentication.",
  },
  {
    id: "preauth_disabled",
    name: "Pre-Authentication Disabled",
    description: "Users with Kerberos pre-authentication disabled.",
    category: "kerberos_delegation",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "kerberos_security",
    objectTypes: ["user"],
    searchScope: "Subtree",
    requiredAttributes: ["userAccountControl"],
    ldapFilter:
      "(&(objectCategory=person)(objectClass=user)(userAccountControl:1.2.840.113556.1.4.803:=4194304))",
    recommendation: "Enable Kerberos pre-authentication.",
  },
  {
    id: "spn_misconfigurations",
    name: "SPN Misconfigurations",
    description: "Malformed, duplicate, or unexpected servicePrincipalName values.",
    category: "kerberos_delegation",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "kerberos_security",
    objectTypes: ["user"],
    searchScope: "Subtree",
    requiredAttributes: ["servicePrincipalName"],
    ldapFilter: "(&(objectCategory=person)(objectClass=user)(servicePrincipalName=*))",
    recommendation: "Correct SPN registrations.",
  },
  {
    id: "constrained_delegation",
    name: "Constrained Delegation",
    description: "Accounts with msDS-AllowedToDelegateTo or constrained delegation UAC.",
    category: "kerberos_delegation",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "delegation_security",
    objectTypes: ["user", "computer"],
    searchScope: "Subtree",
    requiredAttributes: ["msDS-AllowedToDelegateTo", "userAccountControl"],
    ldapFilter: "(|(msDS-AllowedToDelegateTo=*)(userAccountControl:1.2.840.113556.1.4.803:=16777216))",
    recommendation: "Review constrained delegation targets.",
  },
  {
    id: "rbcd",
    name: "Resource-Based Constrained Delegation",
    description: "Objects with msDS-AllowedToActOnBehalfOfOtherIdentity configured.",
    category: "kerberos_delegation",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: false,
    requiresAdLdap: true,
    executionMode: "LDAP",
    moduleId: "delegation_security",
    objectTypes: ["computer"],
    searchScope: "Subtree",
    requiredAttributes: ["msDS-AllowedToActOnBehalfOfOtherIdentity"],
    ldapFilter: "(&(objectCategory=computer)(objectClass=computer)(msDS-AllowedToActOnBehalfOfOtherIdentity=*))",
    recommendation: "Restrict resource-based constrained delegation.",
  },
  // Disabled — Delegation Exposure Summary
  // {
  //   id: "delegation_exposure",
  //   name: "Delegation Exposure Summary",
  //   description: "Summary of delegation types and target services per object.",
  //   category: "kerberos_delegation",
  //   riskLevel: "high",
  //   defaultEnabled: true,
  //   requiresGraph: false,
  //   requiresAdLdap: true,
  //   executionMode: "LDAP",
  //   moduleId: "delegation_security",
  //   requiredAttributes: [
  //     "userAccountControl",
  //     "msDS-AllowedToDelegateTo",
  //     "msDS-AllowedToActOnBehalfOfOtherIdentity",
  //   ],
  //   recommendation: "Review delegation configuration and reduce exposure.",
  // },
  {
    id: "orphan_sids",
    name: "Orphan SID Detection",
    description: "User references to SIDs not present in directory.",
    category: "acl_intelligence",
    riskLevel: "medium",
    defaultEnabled: true,
    requiresGraph: true,
    requiresAdLdap: false,
    executionMode: "GRAPH",
    moduleId: "identity_graph_security",
    requiredAttributes: ["objectSid", "sIDHistory"],
    ldapFilter: null,
    recommendation: "Resolve orphaned SID references to prevent ghost ACL access.",
  },
  {
    id: "shadow_admins",
    name: "Shadow Admin Detection",
    description:
      "Non-admin users with indirect admin-capable paths (graph) or ACL takeover rights (GenericAll, WriteDACL, WriteOwner, GenericWrite).",
    category: "acl_intelligence",
    riskLevel: "critical",
    defaultEnabled: true,
    requiresGraph: true,
    requiresAdLdap: false,
    executionMode: "HYBRID",
    supportsSearchBase: true,
    moduleId: "identity_graph_security",
    objectTypes: ["user"],
    searchScope: "Subtree",
    requiredAttributes: ["memberOf", "objectSid", "nTSecurityDescriptor"],
    ldapFilter: "(&(objectCategory=person)(objectClass=user))",
    recommendation: "Remediate indirect admin rights via nested groups or dangerous ACL grants.",
  },
  {
    id: "sid_history_analysis",
    name: "SID History Analysis",
    description:
      "Accounts with sIDHistory entries, migrated privileged identities, and inherited privileged SIDs.",
    category: "acl_intelligence",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: true,
    requiresAdLdap: false,
    executionMode: "GRAPH",
    moduleId: "identity_graph_security",
    requiredAttributes: ["objectSid", "sIDHistory"],
    ldapFilter: null,
    recommendation:
      "Audit SID history after domain migration; remove stale privileged SID bindings from ACLs.",
  },
  {
    id: "foreign_security_principals",
    name: "Foreign Security Principal Discovery",
    description:
      "ForeignSecurityPrincipals, cross-domain trust references, and orphan foreign principals.",
    category: "acl_intelligence",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: true,
    requiresAdLdap: false,
    executionMode: "GRAPH",
    moduleId: "identity_graph_security",
    requiredAttributes: ["objectSid", "distinguishedName", "memberOf"],
    ldapFilter: "(&(objectClass=foreignSecurityPrincipal))",
    recommendation:
      "Validate trust relationships and remove stale foreign principal mappings.",
  },
  {
    id: "unknown_sid_bindings",
    name: "Unknown SID Binding Detection",
    description: "ACL references to SIDs that cannot be resolved in the synced directory catalog.",
    category: "acl_intelligence",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: true,
    requiresAdLdap: false,
    executionMode: "GRAPH",
    moduleId: "identity_graph_security",
    requiredAttributes: ["nTSecurityDescriptor", "objectSid"],
    ldapFilter: null,
    recommendation:
      "Remove or replace ACE entries referencing unresolvable SIDs to prevent ghost access.",
  },
  {
    id: "broken_acls",
    name: "Broken ACL Detection",
    description:
      "Orphan ACL principals, invalid ACE targets, and stale permissions on parsed security descriptors.",
    category: "acl_intelligence",
    riskLevel: "high",
    defaultEnabled: true,
    requiresGraph: true,
    requiresAdLdap: false,
    executionMode: "GRAPH",
    moduleId: "identity_graph_security",
    requiredAttributes: ["nTSecurityDescriptor", "objectSid"],
    ldapFilter: null,
    recommendation:
      "Repair corrupted or stale ACLs; remove orphan ACE targets and restore expected DACL structure.",
  },
];

function withImplementedFlag(feature) {
  const base = { ...feature, implemented: IMPLEMENTED.has(feature.id) };
  const supportsSearchBase =
    base.supportsSearchBase === true ||
    base.executionMode === "LDAP" ||
    base.executionMode === "HYBRID";

  if (base.executionMode !== "LDAP" && !supportsSearchBase) return base;

  let objectTypes = Array.isArray(base.objectTypes) ? [...base.objectTypes] : null;
  if (!objectTypes?.length) {
    if (base.moduleId === "group_ldap_security") objectTypes = ["group"];
    else if (base.moduleId === "computer_security") objectTypes = ["computer"];
    else if (base.moduleId === "user_account_security") objectTypes = ["user"];
    else if (base.category === "privileged_access") {
      objectTypes = base.id === "nested_privileged_access" ? ["group"] : ["user"];
    } else objectTypes = ["user"];
  }

  return {
    ...base,
    supportsSearchBase,
    objectTypes,
    defaultSearchBaseDn: base.defaultSearchBaseDn || "",
    defaultFilter: base.defaultFilter || base.ldapFilter || null,
    searchScope: base.searchScope || "Subtree",
  };
}

export function getPostureFeatureRegistry() {
  return REGISTRY.map(withImplementedFlag);
}

export function getPostureFeatureById(id) {
  const hit = REGISTRY.find((f) => f.id === id);
  return hit ? withImplementedFlag(hit) : null;
}

export function resolveExecutableFeatureIds(featureIds) {
  const allowed = new Set(IMPLEMENTED);
  const ids = (featureIds || []).map((f) => String(f).trim()).filter(Boolean);
  return [...new Set(ids.filter((id) => allowed.has(id)))];
}

export function buildPostureFeaturesDiscoveryPayload() {
  const features = getPostureFeatureRegistry();
  return {
    categories: POSTURE_FEATURE_CATEGORIES,
    bundles: POSTURE_SCAN_BUNDLES.map((b) => ({
      ...b,
      executableFeatureIds: b.featureIds.filter((fid) => IMPLEMENTED.has(fid)),
      allPlanned: b.planned || b.featureIds.every((fid) => !IMPLEMENTED.has(fid)),
    })),
    features,
    implementedFeatureIds: [...IMPLEMENTED],
    summary: {
      totalFeatures: features.length,
      implementedCount: features.filter((f) => f.implemented).length,
      plannedCount: features.filter((f) => !f.implemented).length,
    },
  };
}
