/** Canonical navigation targets (explicit ids for stable registry references). */
export const NAVIGATION_TARGETS = [
  {
    id: "nav.dashboard",
    kind: "navigation",
    pageId: "Dashboard",
    name: "Dashboard",
    route: "/",
    feFile: "icm-frontend/src/pages/dashboard/Dashboard.jsx",
    primaryApis: ["GET /identities?limit=1", "GET /applications?limit=1"],
    controller: "identityController.getIdentities + applicationController.getApplications",
    metricLabel: "Dashboard_stats_limit1",
    sharedApiIds: [],
    fe: {
      reactQuery: false,
      mountApiCalls: 2,
      duplicateRisk: "low",
      primaryApis: ["GET /identities?limit=1", "GET /applications?limit=1"],
    },
    narrative: {
      oneliner: "Mount is light KPI counts; not a priority.",
      fePattern: "useEffect dual fetch for KPI tiles",
    },
    enabled: true,
    measurement: { mode: "mongo", driver: "mongo" },
  },
  {
    id: "nav.allIdentities",
    kind: "navigation",
    pageId: "AllIdentities",
    name: "All Identities",
    route: "/identities",
    feFile: "icm-frontend/src/pages/identities/IdentitiesList.jsx",
    primaryApis: ["GET /identities"],
    controller: "identityController.getIdentities",
    metricLabel: "AllIdentities_page10",
    sharedApiIds: ["api.identities.list"],
    fe: {
      reactQuery: true,
      mountApiCalls: 3,
      duplicateRisk: "low",
      primaryApis: ["GET /identities", "GET meta fields", "lock status"],
      listFieldsHint:
        "employeeId,userId,firstname,lastname,email,displayName,department,title,location,status,country,phoneNo,managerId,mangerName,costCenter,hierDate,terminationDate",
      uiSort: { sortBy: "displayName", sortDir: "asc" },
    },
    narrative: { oneliner: "Layered grades from live probe.", reactQuery: "Yes" },
    enabled: true,
    measurement: { mode: "controller", driver: "controller" },
  },
  {
    id: "nav.identityProfiles",
    kind: "navigation",
    pageId: "IdentityProfiles",
    name: "Identity Profiles",
    route: "/identities/profiles",
    feFile: "icm-frontend/src/pages/identities/IdentityProfileList.jsx",
    primaryApis: ["GET /identity-profiles"],
    controller: "identityProfileController.getIdentityProfiles",
    metricLabel: "IdentityProfiles_list",
    fe: { reactQuery: false, mountApiCalls: 2, duplicateRisk: "low", primaryApis: ["GET /identity-profiles"] },
    enabled: true,
  },
  {
    id: "nav.correlatedAccounts",
    kind: "navigation",
    pageId: "CorrelatedAccounts",
    name: "Correlated Accounts",
    route: "/identities/correlated",
    feFile: "icm-frontend/src/pages/identities/CorrelatedAccounts.jsx",
    primaryApis: ["GET /correlation/correlated-accounts"],
    controller: "correlationController.getCorrelatedAccounts",
    metricLabel: "CorrelatedAccounts_page10",
    fe: { reactQuery: false, mountApiCalls: 2, duplicateRisk: "medium", primaryApis: ["GET /correlation/correlated-accounts"] },
    enabled: true,
  },
  {
    id: "nav.uncorrelatedAccounts",
    kind: "navigation",
    pageId: "UncorrelatedAccounts",
    name: "Uncorrelated Accounts",
    route: "/identities/orphans",
    feFile: "icm-frontend/src/pages/identities/UncorrelatedAccounts.jsx",
    primaryApis: ["GET /correlation/orphans"],
    controller: "orphanController",
    metricLabel: "UncorrelatedAccounts_page10",
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /correlation/orphans"] },
    enabled: true,
  },
  {
    id: "nav.duplicateAppAccounts",
    kind: "navigation",
    pageId: "DuplicateAppAccounts",
    name: "Duplicate App Accounts",
    route: "/identities/application-user-duplicates",
    feFile: "icm-frontend/src/pages/identities/ApplicationUserDuplicatesPage.jsx",
    primaryApis: ["GET /applications/:id/user-duplicates"],
    controller: "applicationController",
    metricLabel: "DuplicateAppAccounts_page10",
    fe: { reactQuery: false, mountApiCalls: 2, duplicateRisk: "low", primaryApis: ["GET /applications/:id/user-duplicates"] },
    enabled: true,
  },
  {
    id: "nav.peerComparison",
    kind: "navigation",
    pageId: "PeerComparison",
    name: "Peer Comparison",
    route: "/identities/peer-comparison",
    feFile: "icm-frontend/src/pages/identities/PeerComparison.jsx",
    primaryApis: ["GET /identities"],
    controller: "identityController.getIdentities",
    metricLabel: "AllIdentities_page10",
    sharedApiIds: ["api.identities.list"],
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /identities"] },
    enabled: true,
  },
  {
    id: "nav.identityPosture",
    kind: "navigation",
    pageId: "IdentityPosture",
    name: "Identity Posture",
    route: "/identities/posture",
    feFile: "icm-frontend/src/pages/identities/IdentityPosture.jsx",
    primaryApis: ["GET /identities"],
    controller: "identityController.getIdentities",
    metricLabel: "AllIdentities_page10",
    sharedApiIds: ["api.identities.list"],
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /identities"] },
    enabled: true,
  },
  {
    id: "nav.applications",
    kind: "navigation",
    pageId: "Applications",
    name: "Applications",
    route: "/applications",
    feFile: "icm-frontend/src/pages/applications/AppRegistry.jsx",
    primaryApis: ["GET /applications"],
    controller: "applicationController.getApplications",
    metricLabel: "Applications_page10",
    sharedApiIds: ["api.applications.list"],
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /applications"] },
    narrative: { oneliner: "Application registry list — detail tabs are separate feature targets." },
    enabled: true,
    measurement: { mode: "controller", driver: "controller" },
  },
  {
    id: "nav.entitlements",
    kind: "navigation",
    pageId: "Entitlements",
    name: "Entitlements",
    route: "/access/entitlements",
    feFile: "icm-frontend/src/pages/Entitlements/CorrelatedEntitlements.jsx",
    primaryApis: ["GET /applications", "GET /applications/:id/correlations"],
    controller: "appCorrelationController.getCorrelationResults",
    metricLabel: "Entitlements_correlation_page10",
    sharedApiIds: ["api.applications.list"],
    fe: {
      reactQuery: false,
      mountApiCalls: 2,
      duplicateRisk: "medium",
      primaryApis: ["GET /applications", "GET /applications/:id/correlations"],
    },
    enabled: true,
  },
  {
    id: "nav.securityDashboard",
    kind: "navigation",
    pageId: "SecurityDashboard",
    name: "Security Dashboard",
    route: "/security/dashboard",
    feFile: "icm-frontend/src/pages/security/dashboard/SecurityDashboard.jsx",
    primaryApis: ["GET /security/applications/:id/overview", "GET /security/applications/:id/findings"],
    controller: "securityController.getApplicationSecurityOverview",
    metricLabel: "SecurityFindings_page10",
    sharedApiIds: ["api.security.findings"],
    fe: {
      reactQuery: true,
      mountApiCalls: 2,
      duplicateRisk: "low",
      primaryApis: ["GET /security/applications/:id/overview", "GET .../findings"],
    },
    enabled: true,
  },
  {
    id: "nav.findingsExplorer",
    kind: "navigation",
    pageId: "FindingsExplorer",
    name: "Findings Explorer",
    route: "/security/findings",
    feFile: "icm-frontend/src/pages/security/findings/FindingsExplorer.jsx",
    primaryApis: ["GET /security/applications/:id/findings"],
    controller: "securityController.getApplicationSecurityFindings",
    metricLabel: "SecurityFindings_page10",
    sharedApiIds: ["api.security.findings"],
    fe: { reactQuery: true, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /security/applications/:id/findings"] },
    enabled: true,
  },
  {
    id: "nav.scanCenter",
    kind: "navigation",
    pageId: "ScanCenter",
    name: "Scan Center",
    route: "/security/scans",
    feFile: "icm-frontend/src/pages/security/scans/ScanCenter.jsx",
    primaryApis: ["GET /security/applications/:id/scans"],
    controller: "securityController.listScans",
    metricLabel: "SecurityScans_list",
    fe: { reactQuery: true, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /security/applications/:id/scans"] },
    enabled: true,
  },
  {
    id: "nav.policyCenter",
    kind: "navigation",
    pageId: "PolicyCenter",
    name: "Policy Center",
    route: "/security/policies",
    feFile: "icm-frontend/src/pages/security/policies/PolicyCenter.jsx",
    primaryApis: ["GET /security/policies"],
    controller: "securityController",
    metricLabel: "SecurityPolicies_list",
    fe: { reactQuery: true, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /security/policies"] },
    enabled: true,
  },
  {
    id: "nav.groupIntelligence",
    kind: "navigation",
    pageId: "GroupIntelligence",
    name: "Group Intelligence",
    route: "/security/groups",
    feFile: "icm-frontend/src/pages/security/groups/GroupIntelligenceView.jsx",
    primaryApis: ["GET /security/applications/:id/findings"],
    controller: "securityController",
    metricLabel: "SecurityFindings_page10",
    sharedApiIds: ["api.security.findings"],
    fe: { reactQuery: true, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /security/applications/:id/findings"] },
    enabled: true,
  },
  {
    id: "nav.sodPolicies",
    kind: "navigation",
    pageId: "SodPolicies",
    name: "SoD Policies",
    route: "/governance/sod-policies",
    primaryApis: ["GET /sod/policies"],
    metricLabel: "SodPolicies_list",
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /sod/policies"] },
    enabled: true,
  },
  {
    id: "nav.sodViolations",
    kind: "navigation",
    pageId: "SodViolations",
    name: "SoD Violations",
    route: "/governance/sod-violations",
    primaryApis: ["GET /sod/violations"],
    metricLabel: "SodViolations_page10",
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /sod/violations"] },
    enabled: true,
  },
  {
    id: "nav.workflows",
    kind: "navigation",
    pageId: "Workflows",
    name: "Workflows",
    route: "/governance/workflows",
    primaryApis: ["GET /remediation-workflows/workflows"],
    metricLabel: "Workflows_list",
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /remediation-workflows/workflows"] },
    enabled: true,
  },
  {
    id: "nav.transforms",
    kind: "navigation",
    pageId: "Transforms",
    name: "Transforms",
    route: "/governance/transforms",
    primaryApis: ["GET /transforms"],
    metricLabel: "Transforms_list",
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /transforms"] },
    enabled: true,
  },
  {
    id: "nav.accessCertification",
    kind: "navigation",
    pageId: "AccessCertification",
    name: "Access Certification",
    route: "/governance/certifications/access",
    primaryApis: ["GET /access-certification/campaigns"],
    controller: "campaignController.getAllCampaigns",
    metricLabel: "AccessCertCampaigns_list",
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /access-certification/campaigns"] },
    enabled: true,
    measurement: { mode: "controller", driver: "controller" },
  },
  {
    id: "nav.remediationEvents",
    kind: "navigation",
    pageId: "RemediationEvents",
    name: "Remediation Events",
    route: "/governance/remediation-events",
    primaryApis: ["GET executions", "GET tasks"],
    metricLabel: "RemediationEvents_dual",
    fe: { reactQuery: false, mountApiCalls: 2, duplicateRisk: "medium", primaryApis: ["GET executions", "GET tasks"] },
    enabled: true,
  },
  {
    id: "nav.privilegedEntitlements",
    kind: "navigation",
    pageId: "PrivilegedEntitlements",
    name: "Privileged Entitlements",
    route: "/governance/discovery/privileged-entitlement",
    primaryApis: ["GET /discovery/policies?type=ENTITLEMENT"],
    metricLabel: "DiscoveryPolicies_list",
    sharedApiIds: ["api.discovery.policies"],
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /discovery/policies?type=ENTITLEMENT"] },
    enabled: true,
  },
  {
    id: "nav.privilegedUsers",
    kind: "navigation",
    pageId: "PrivilegedUsers",
    name: "Privileged Users",
    route: "/governance/discovery/privileged-user",
    primaryApis: ["GET /discovery/policies?type=USER"],
    metricLabel: "DiscoveryPolicies_list",
    sharedApiIds: ["api.discovery.policies"],
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /discovery/policies?type=USER"] },
    enabled: true,
  },
  {
    id: "nav.dataHygiene",
    kind: "navigation",
    pageId: "DataHygiene",
    name: "Data Hygiene",
    route: "/datahygine",
    primaryApis: ["GET /data-hygiene/summary"],
    metricLabel: "DataHygiene_summary",
    fe: {
      reactQuery: false,
      mountApiCalls: 1,
      duplicateRisk: "low",
      primaryApis: ["GET /data-hygiene/summary"],
      notes: "Serves Mongo snapshot (data_hygiene_tenant_summaries); refresh=1 forces recompute",
    },
    enabled: true,
    measurement: { mode: "controller", driver: "controller" },
  },
  {
    id: "nav.auditLog",
    kind: "navigation",
    pageId: "AuditLog",
    name: "Audit Log",
    route: "/reports/audit",
    primaryApis: ["GET /audit"],
    metricLabel: "AuditLog_page10",
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /audit"] },
    enabled: true,
  },
  {
    id: "nav.activityFeed",
    kind: "navigation",
    pageId: "ActivityFeed",
    name: "Activity Feed",
    route: "/reports/activity",
    primaryApis: ["GET /activity"],
    metricLabel: "ActivityFeed_page10",
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /activity"] },
    enabled: true,
  },
  {
    id: "nav.isoReport",
    kind: "navigation",
    pageId: "IsoReport",
    name: "ISO Report",
    route: "/reports/iso-2007",
    primaryApis: ["GET /applications", "per-app ISO APIs"],
    metricLabel: "IsoReport_mount_fanout",
    sharedApiIds: ["api.applications.list"],
    fe: { reactQuery: true, mountApiCalls: 6, duplicateRisk: "high", primaryApis: ["GET /applications", "per-app ISO APIs"] },
    enabled: true,
  },
  {
    id: "nav.connectors",
    kind: "navigation",
    pageId: "Connectors",
    name: "Connectors",
    route: "/admin/integrations/connectors",
    primaryApis: ["GET /connectors"],
    metricLabel: "Connectors_list",
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /connectors"] },
    enabled: true,
  },
  {
    id: "nav.usersRoles",
    kind: "navigation",
    pageId: "UsersRoles",
    name: "Users & Roles",
    route: "/admin/users",
    primaryApis: ["GET /auth/users"],
    metricLabel: "UsersRoles_list",
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /auth/users"] },
    enabled: true,
  },
  {
    id: "nav.correlationEngine",
    kind: "navigation",
    pageId: "CorrelationEngine",
    name: "Correlation Engine",
    route: "/identities/correlation",
    primaryApis: ["GET /applications", "GET /identity-profiles"],
    metricLabel: "CorrelationEngine_mount",
    sharedApiIds: ["api.applications.list"],
    fe: { reactQuery: false, mountApiCalls: 2, duplicateRisk: "low", primaryApis: ["GET /applications", "GET /identity-profiles"] },
    enabled: true,
  },
  {
    id: "nav.identityMindmap",
    kind: "navigation",
    pageId: "IdentityMindmap",
    name: "Identity Mindmap",
    route: "/identities/mindmap",
    primaryApis: ["GET /identities"],
    metricLabel: "MindmapSearch_identities50",
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /identities"] },
    enabled: true,
  },
  {
    id: "nav.ADSecurity",
    kind: "navigation",
    pageId: "ADSecurity",
    name: "Identity Sphere",
    route: "/identities/sphere",
    comingSoon: true,
    enabled: true,
    narrative: { oneliner: "Coming soon shell — no API measured." },
  },
  {
    id: "nav.certificationsHub",
    kind: "navigation",
    pageId: "CertificationsHub",
    name: "Certifications Hub",
    route: "/governance/certifications",
    comingSoon: true,
    enabled: true,
    narrative: { oneliner: "Nav shell — see AccessCertification for data page." },
  },
];
