/**
 * Application detail feature targets (Level 2).
 * Parent: nav.applications — tabs in ApplicationDetail.jsx
 */

export const APPLICATION_FEATURE_TARGETS = [
  {
    id: "feat.applications.accounts",
    kind: "feature",
    name: "Accounts Tab",
    parentId: "nav.applications",
    route: "/applications/:id?tab=users",
    feFile: "icm-frontend/src/pages/applications/UsersTable.jsx",
    trigger: { type: "tab", key: "users", label: "Current accounts" },
    primaryApis: ["GET /applications/:id/users"],
    controller: "applicationController.getApplicationUsers",
    metricLabel: "Applications_Accounts_page10",
    sharedApiIds: ["api.applications.users"],
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /applications/:id/users"] },
    measurement: { mode: "mongo", driver: "mongo" },
    enabled: true,
  },
  {
    id: "feat.applications.entitlements",
    kind: "feature",
    name: "Entitlements Tab",
    parentId: "nav.applications",
    route: "/applications/:id?tab=entitlements",
    feFile: "icm-frontend/src/pages/applications/EntitlementsTable.jsx",
    trigger: { type: "tab", key: "entitlements", label: "Entitlements" },
    primaryApis: ["GET /applications/:id/entitlements"],
    controller: "applicationController.getApplicationEntitlements",
    metricLabel: "Applications_Entitlements_page10",
    sharedApiIds: ["api.applications.entitlements"],
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /applications/:id/entitlements"] },
    measurement: { mode: "mongo", driver: "mongo" },
    enabled: true,
  },
  {
    id: "feat.applications.reconHistory",
    kind: "feature",
    name: "Reconciliation History",
    parentId: "nav.applications",
    route: "/applications/:id?tab=reconHistory",
    feFile: "icm-frontend/src/pages/applications/ReconciliationHistoryTable.jsx",
    trigger: { type: "tab", key: "reconHistory", label: "Reconciliation history" },
    primaryApis: ["GET /applications/:id/reconciliation/runs"],
    controller: "reconciliationController.listReconciliationRuns",
    metricLabel: "Applications_ReconHistory_page10",
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /applications/:id/reconciliation/runs"] },
    measurement: { mode: "mongo", driver: "mongo" },
    enabled: true,
  },
  {
    id: "feat.applications.changeLogs",
    kind: "feature",
    name: "Change Logs",
    parentId: "nav.applications",
    route: "/applications/:id?tab=deltaChanges",
    feFile: "icm-frontend/src/pages/applications/DeltaChangesTable.jsx",
    trigger: { type: "tab", key: "deltaChanges", label: "Change logs" },
    primaryApis: ["GET /applications/:id/reconciliation/deltas"],
    controller: "reconciliationController.listReconciliationDeltas",
    metricLabel: "Applications_ChangeLogs_page10",
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /applications/:id/reconciliation/deltas"] },
    measurement: { mode: "mongo", driver: "mongo" },
    enabled: true,
  },
  {
    id: "feat.applications.correlation",
    kind: "feature",
    name: "Correlation",
    parentId: "nav.applications",
    route: "/applications/:id?tab=correlation",
    feFile: "icm-frontend/src/pages/applications/AppCorrelationConfig.jsx",
    trigger: { type: "tab", key: "correlation", label: "Correlation" },
    primaryApis: ["GET /applications/:id/correlations"],
    controller: "appCorrelationController",
    metricLabel: "Applications_Correlation_page10",
    fe: { reactQuery: false, mountApiCalls: 2, duplicateRisk: "medium", primaryApis: ["GET /applications/:id/correlations"] },
    measurement: { mode: "mongo", driver: "mongo" },
    enabled: true,
  },
  {
    id: "feat.applications.adSuggestions",
    kind: "feature",
    name: "AD Suggestions",
    parentId: "nav.applications",
    route: "/applications/:id?tab=adSuggestions",
    feFile: "icm-frontend/src/pages/applications/ApplicationDetail.jsx",
    trigger: { type: "tab", key: "adSuggestions", label: "AD suggestions" },
    primaryApis: ["GET /applications/:id (AD suggestion attrs)"],
    metricLabel: "Applications_AdSuggestions_page10",
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: [] },
    measurement: { mode: "mongo", driver: "mongo" },
    enabled: true,
  },
  {
    id: "feat.applications.settings",
    kind: "feature",
    name: "Settings",
    parentId: "nav.applications",
    route: "/applications/:id?tab=settings",
    feFile: "icm-frontend/src/pages/applications/ApplicationDetail.jsx",
    trigger: { type: "tab", key: "settings", label: "Settings" },
    primaryApis: ["GET /applications/:id"],
    controller: "applicationController.getApplicationById",
    metricLabel: "Applications_Settings_load",
    fe: { reactQuery: false, mountApiCalls: 1, duplicateRisk: "low", primaryApis: ["GET /applications/:id"] },
    measurement: { mode: "mongo", driver: "mongo" },
    enabled: true,
  },
];
